export enum ActivityAction {
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  DELETED = "DELETED",
  OPENED = "OPENED",
  CLOSED = "CLOSED",
  ACTIVATED = "ACTIVATED",
  DEACTIVATED = "DEACTIVATED",
  RECORDED = "RECORDED",
  ADDED = "ADDED"
}